### ISSUE TITLE
Null is not an object (evaluating 'RNSslPinning.fetch')

### ISSUE THREAD

**Issue by AlbertoGuastalla** [MaxToyberman/react-native-ssl-pinning#90]
Hi, I was trying to pin a self signed certificate inside my react-native app using your "react-native-ssl-pinning" library. The problem is that when I launch the fetch, I get an error like this: "null is not an object (evaluating 'RNSslPinning.fetch')". I searched the internet and found nothing.

Thanks in advice.

**Comment by quanvanbinh** [comment]
Same error as Albert. Looking forward for fixing this issue soon. Thank you

**Comment by shahdeys** [comment]
I have the same exact issue. 

I have a fresh project, and I don't see this kind of "ios" folder. I am not using any pre-existing assets. I'm using Expo CLI and React Native (latest versions) to write my code. I'm also using the latest version of react-native-ssl-pinning.

Why am I still seeing this error? 

I see inside node_modules an ios and android folder. 

```~/shahdeys_directory/node_modules/react-native-ssl-pinning/ios```

However, in this directory, when I try to run `pod install` it does not work and throws me this error:

``` [!] No `Podfile' found in the project directory. ```

**Comment by kraj011** [comment]
@shahdeys When you use expo, it removed the ios and android folders because with expo the whole point is you don't need to look / mess with native code. I use this library in a project of mine without expo and it works great. If you want, try ejecting from expo: [look here](https://docs.expo.io/bare/customizing/) and then, once you have the ios folder, cd into it and pod install.
